// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/baggage": {
            "get": {
                "description": "Возращает список всех активных багажей",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Получение списка багажа",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код багажа",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.BaggagesGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/baggage/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Создает новый багаж с предоставленными данными",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Создание нового багажа",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код багажа",
                        "name": "searchCode",
                        "in": "query"
                    },
                    {
                        "description": "Пользовательский объект в формате JSON",
                        "name": "baggage",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BaggageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.BaggagesGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/baggage/{baggage_id}": {
            "get": {
                "description": "Возвращает информацию о багаже по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Получение багажа по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID багажа",
                        "name": "baggage_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о багаже",
                        "schema": {
                            "$ref": "#/definitions/model.Baggage"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/baggage/{baggage_id}/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет багаж по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Удаление багажа",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID багажа",
                        "name": "baggage_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код багажа",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.BaggagesGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/baggage/{baggage_id}/delivery": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет багаж к доставке по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Добавление багажа к доставке",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID багажа",
                        "name": "baggage_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код багажа",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.BaggagesGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет багаж из доставки по его ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Удаление багажа из доставки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID багажа",
                        "name": "baggage_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Код багажа",
                        "name": "searchCode",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.BaggagesGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/baggage/{baggage_id}/image": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Добавляет изображение к багажу по его ID",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Добавление изображения к багажу",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID багажа",
                        "name": "baggage_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Изображение багажа",
                        "name": "image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о багаже с изображением",
                        "schema": {
                            "$ref": "#/definitions/model.Baggage"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/baggage/{baggage_id}/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет информацию о багаже по его ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Багаж"
                ],
                "summary": "Обновление информации о багаже",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID багажа",
                        "name": "baggage_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о багаже",
                        "schema": {
                            "$ref": "#/definitions/model.Baggage"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "У пользователя нет прав для этого запроса",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delivery": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает список всех не удаленных доставок",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Доставка"
                ],
                "summary": "Получение списка доставок",
                "parameters": [
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Номер рейса",
                        "name": "searchFlightNumber",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Начало даты формирования",
                        "name": "startFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Конец даты формирования",
                        "name": "endFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Статус доставки",
                        "name": "deliveryStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список доставок",
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryRequest"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delivery/{delivery_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Возвращает информацию о доставке по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Доставка"
                ],
                "summary": "Получение доставки по идентификатору",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор доставки",
                        "name": "delivery_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delivery/{delivery_id}/delete": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Удаляет доставку по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Доставка"
                ],
                "summary": "Удаление доставки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор доставки",
                        "name": "delivery_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Номер рейса",
                        "name": "searchFlightNumber",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Начало даты формирования",
                        "name": "startFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Конец даты формирования",
                        "name": "endFormationDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "format": "email",
                        "description": "Статус доставки",
                        "name": "deliveryStatus",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список багажей",
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryRequest"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delivery/{delivery_id}/status/moderator": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет статус доставки для модератора по идентификатору доставки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Доставка"
                ],
                "summary": "Обновление статуса доставки для модератора",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор доставки",
                        "name": "delivery_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый статус доставки",
                        "name": "deliveryStatus",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryUpdateStatusRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delivery/{delivery_id}/status/user": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет статус доставки для пользователя по идентификатору доставки",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Доставка"
                ],
                "summary": "Обновление статуса доставки для пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор доставки",
                        "name": "delivery_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delivery/{delivery_id}/update": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Обновляет номер рейса для доставки по её идентификатору",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Доставка"
                ],
                "summary": "Обновление номера рейса доставки",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Идентификатор доставки",
                        "name": "delivery_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Новый номер рейса",
                        "name": "flightNumber",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryUpdateFlightNumberRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о доставке",
                        "schema": {
                            "$ref": "#/definitions/model.DeliveryGetResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не авторизован",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Авторизация пользователя и генерация JWT-токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Вход пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен",
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Выход пользователя из системы и удаление токена из куков",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Выход пользователя",
                "responses": {
                    "200": {
                        "description": "Успешный ответ",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Регистрация нового пользователя с предоставленной информацией.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Пользователь"
                ],
                "summary": "Регистрация нового пользователя.",
                "parameters": [
                    {
                        "description": "Пользовательский объект в формате JSON",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Токен",
                        "schema": {
                            "$ref": "#/definitions/model.UserLoginResponse"
                        }
                    },
                    "400": {
                        "description": "Обработанная ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Baggage": {
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string",
                    "example": "AirlineX"
                },
                "baggage_code": {
                    "type": "string",
                    "example": "ABC123"
                },
                "baggage_id": {
                    "type": "integer"
                },
                "baggage_status": {
                    "type": "string",
                    "example": "checked"
                },
                "baggage_type": {
                    "type": "string",
                    "example": "suitcase"
                },
                "owner_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "pasport_details": {
                    "type": "string",
                    "example": "123456789"
                },
                "photo": {
                    "type": "string",
                    "example": "http://example.com/baggage.jpg"
                },
                "size": {
                    "type": "string",
                    "example": "large"
                },
                "weight": {
                    "type": "number",
                    "example": 23.5
                }
            }
        },
        "model.BaggageRequest": {
            "type": "object",
            "properties": {
                "airline": {
                    "type": "string",
                    "example": "AirlineX"
                },
                "baggage_code": {
                    "type": "string",
                    "example": "ABC123"
                },
                "baggage_type": {
                    "type": "string",
                    "example": "suitcase"
                },
                "owner_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "pasport_details": {
                    "type": "string",
                    "example": "123456789"
                },
                "size": {
                    "type": "string",
                    "example": "large"
                },
                "weight": {
                    "type": "number",
                    "example": 23.5
                }
            }
        },
        "model.BaggagesGetResponse": {
            "type": "object",
            "properties": {
                "baggages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Baggage"
                    }
                },
                "delivery_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "model.DeliveryGetResponse": {
            "type": "object",
            "properties": {
                "baggages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Baggage"
                    }
                },
                "completion_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "delivery_id": {
                    "type": "integer"
                },
                "delivery_status": {
                    "type": "string"
                },
                "flight_number": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "model.DeliveryRequest": {
            "type": "object",
            "properties": {
                "completion_date": {
                    "type": "string"
                },
                "creation_date": {
                    "type": "string"
                },
                "delivery_id": {
                    "type": "integer"
                },
                "delivery_status": {
                    "type": "string"
                },
                "flight_number": {
                    "type": "string"
                },
                "formation_date": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                }
            }
        },
        "model.DeliveryUpdateFlightNumberRequest": {
            "type": "object",
            "properties": {
                "flight_number": {
                    "type": "string"
                }
            }
        },
        "model.DeliveryUpdateStatusRequest": {
            "type": "object",
            "properties": {
                "delivery_status": {
                    "type": "string"
                }
            }
        },
        "model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "model.Role": {
            "type": "string",
            "enum": [
                "пользователь",
                "модератор"
            ],
            "x-enum-varnames": [
                "UserRole",
                "ModeratorRole"
            ]
        },
        "model.UserLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "model.UserLoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/model.Role"
                }
            }
        },
        "model.UserRegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "http://localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "BagTracker RestAPI",
	Description:      "API server for BagTracker application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
